name: "CI"

on: push

jobs:
  build:
    name: "ğŸ—ï¸ Gradle assemble"
    runs-on: ubuntu-latest
    steps:
      - name: "ğŸ“¥ Check-out"
        uses: actions/checkout@v4
      - name: "ğŸ§° Set up JDK 16"
        uses: actions/setup-java@v4
        with:
          java-version: 16
          distribution: temurin
      - name: "ğŸ’ª Grant execute permission for gradlew"
        run: "chmod +x gradlew"
      - name: "ğŸ—ï¸ Build with Gradle"
        run: "./gradlew assemble"
  test:
    needs: build
    name: "âœ… Gradle test"
    runs-on: ubuntu-latest
    steps:
      - name: "ğŸ“¥ Check-out"
        uses: actions/checkout@v4
      - name: "ğŸ§° Set up JDK 16"
        uses: actions/setup-java@v4
        with:
          java-version: 16
          distribution: temurin
      - name: "ğŸ’ª Grant execute permission for gradlew"
        run: "chmod +x gradlew"
      - name: "âœ… Test with Gradle"
        run: "./gradlew test"
